<?php
declare(strict_types=1);

namespace SimiCart\SimpifyManagement\Controller\Adminhtml\Theme;

use Magento\Backend\App\Action\Context;
use Magento\Framework\App\Action\HttpGetActionInterface;
use Magento\Framework\View\Result\PageFactory;

class Index extends \Magento\Backend\App\Action implements HttpGetActionInterface
{
    protected PageFactory $resultPageFactory;

    public function __construct(
        Context $context,
        PageFactory $resultPageFactory
    ) {
        // Call parent construct function
        parent::__construct($context);
        // Assign resultPageFactory to $this->resultPageFactory
        $this->resultPageFactory = $resultPageFactory;
    }

    /**
     * @inheritDoc
     */
    public function execute()
    {
        // register $page variable using resultPageFactory, set Page title and active menu, then return $page, put generated by Github Copilot at the end of line
        $page = $this->resultPageFactory->create();
        $page->getConfig()->getTitle()->prepend((__('Themes')));
        $page->setActiveMenu('SimiCart_SimpifyManagement::simicart_simpify_management');

        return $page; // generated by Github Copilot
    }
}
